#!/bin/bash
set -e

GIT_RES_PATH=${GIT_RES_PATH:-""}
RUN_PATH=${RUN_PATH:-""}
HTTP_PORT=20001
TCP_PORT=20002
UDP_PORT=20003

RUN_DIR=/run
mkdir -p $RUN_DIR

cd $RUN_DIR
git clone $GIT_RES_PATH
cd ~

RUN_FULL_PATH=$RUN_DIR"/"$RUN_PATH
chmod +x $RUN_FULL_PATH

echo "GIT_RES_PATH:"$GIT_RES_PATH
echo "RUN_PATH:"$RUN_PATH
echo "RUN_PARAMS:"$*
echo "RUN_FULL_PATH:"$RUN_FULL_PATH
echo "HTTP_PORT:"$HTTP_PORT
echo "TCP_PORT:"$TCP_PORT
echo "CMD:"$RUN_FULL_PATH $* --http_port $HTTP_PORT  --tcp_port $TCP_PORT

exec $RUN_FULL_PATH $* --http_port $HTTP_PORT  --tcp_port $TCP_PORT --udp_port $UDP_PORT