#!/bin/bash
set -e

ADMIN_PASSWD=${ADMIN_PASSWD:-}
MYSQL_HOST=${MYSQL_HOST:-}
MYSQL_PORT=${MYSQL_PORT:-"3306"}
MYSQL_USER=${MYSQL_USER:-}
MYSQL_PASS=${MYSQL_PASS:-}
MYSQL_DB=${MYSQL_DB:-"openfire"}

USERSERVICE_ENABLE=${USERSERVICE_ENABLE:-"true"}
USER_SERVICE_SECRET=${USER_SERVICE_SECRET:-"qOAWYYau"}
XMPP_DOMAIN=${XMPP_DOMAIN:-}


# Mysql command.
MYSQL_CONN="mysql -h$MYSQL_HOST -u$MYSQL_USER -P$MYSQL_PORT -p$MYSQL_PASS"
$($MYSQL_CONN -e exit)

check_db() {
  # Create, import database template.
  echo "Create database!!!"
  $MYSQL_CONN -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DB ;" 2>/dev/null
  echo "Check database!!!"
  mysql_create_status=`echo $?`
  if [ $mysql_create_status -ne 0 ]; then
    echo 'ERROR: Cannot create the database.'
    exit 1
  fi
  
}

update_conf(){
  echo "update_conf"
  openfire_xml_path="openfire/conf/openfire.xml"
  echo "openfire_xml_path,"$openfire_xml_path
  sed -Ei "s/#OF_CONF_DB_HOST#/$MYSQL_HOST/" $openfire_xml_path && \
  sed -Ei "s/#OF_CONF_DB_PORT#/$MYSQL_PORT/" $openfire_xml_path && \
  sed -Ei "s/#OF_CONF_DB_USER_REPLACE#/$MYSQL_USER/" $openfire_xml_path && \
  sed -Ei "s/#OF_CONF_DB_PASS_REPLACE#/$MYSQL_PASS/" $openfire_xml_path && \
  sed -Ei "s/#OF_CONF_DB_NAME#/$MYSQL_DB/" $openfire_xml_path
}

update_db(){
  echo "REPLACE INTO $MYSQL_DB.ofProperty(name, propValue) VALUES (\"plugin.userservice.enabled\", \"$USERSERVICE_ENABLE\");"
  $MYSQL_CONN -e "REPLACE INTO $MYSQL_DB.ofProperty(name, propValue) VALUES (\"plugin.userservice.enabled\", \"$USERSERVICE_ENABLE\");"
  echo "REPLACE INTO $MYSQL_DB.ofProperty(name, propValue) VALUES (\"plugin.userservice.secret\", \"$USER_SERVICE_SECRET\");"
  $MYSQL_CONN -e "REPLACE INTO $MYSQL_DB.ofProperty(name, propValue) VALUES (\"plugin.userservice.secret\", \"$USER_SERVICE_SECRET\");"
  echo "REPLACE INTO $MYSQL_DB.ofProperty(name, propValue) VALUES (\"xmpp.domain\", \"$XMPP_DOMAIN\");"
  $MYSQL_CONN -e "REPLACE INTO $MYSQL_DB.ofProperty(name, propValue) VALUES (\"xmpp.domain\", \"$XMPP_DOMAIN\");"
}

set_admin_passwd(){
  if [[ $ADMIN_PASSWD != "" ]]; then
    openfire_mysql_path="openfire/resources/database/openfire_mysql.sql"
    echo "openfire_mysql_path,"$openfire_mysql_path
    sed -Ei "s/'admin', 'admin', 'Administrator',/'admin', '$ADMIN_PASSWD', 'Administrator',/" $openfire_mysql_path
  fi
}

check_db
update_conf
set_admin_passwd

chmod +x openfire/bin/openfire


echo "start openfire..."
bash openfire/bin/openfire start
echo "sleep 10..."
sleep 10
echo "stop openfire..."
bash openfire/bin/openfire stop
echo "update_db...."
update_db
echo "restart openfire..."
bash openfire/bin/openfire start
tail -f openfire/logs/error.log

