#!/bin/bash
set -e

OPENFIRE_USER=openfire
OPENFIRE_LOG_DIR=/var/log/openfire

ADMIN_PASSWD=${ADMIN_PASSWD:-}
MYSQL_HOST=${MYSQL_HOST:-}
MYSQL_PORT=${MYSQL_PORT:-"3306"}
MYSQL_USER=${MYSQL_USER:-}
MYSQL_PASS=${MYSQL_PASS:-}
MYSQL_DB=${MYSQL_DB:-"openfire"}

USERSERVICE_ENABLE=${USERSERVICE_ENABLE:-"true"}
USER_SERVICE_SECRET=${USER_SERVICE_SECRET:-"qOAWYYau"}
XMPP_DOMAIN=${XMPP_DOMAIN:-}


# Mysql command.
MYSQL_CONN="mysql -h$MYSQL_HOST -u$MYSQL_USER -P$MYSQL_PORT -p$MYSQL_PASS"
$($MYSQL_CONN -e exit)


create_log_dir() {
  echo "Initializing ${OPENFIRE_LOG_DIR}..."
  mkdir -p ${OPENFIRE_LOG_DIR}
  chmod -R 0755 ${OPENFIRE_LOG_DIR}
  chown -R ${OPENFIRE_USER}:${OPENFIRE_USER} ${OPENFIRE_LOG_DIR}
}

check_db() {
  # Drop and create, import database template.
  echo "Drop database!!!"
  $MYSQL_CONN -e "DROP DATABASE IF EXISTS $MYSQL_DB ;" 2>/dev/null
  echo "Create database!!!"
  $MYSQL_CONN -e "CREATE DATABASE $MYSQL_DB ;" 2>/dev/null
  echo "Check database!!!"
  mysql_create_status=`echo $?`
  if [ $mysql_create_status -ne 0 ]; then
    echo 'ERROR: Cannot create the database.'
    exit 1
  fi
}

update_conf(){
  echo "update_conf"
  sed -Ei "s/#OF_CONF_DB_HOST#/$MYSQL_HOST/" /data/etc/openfire.xml && \
  sed -Ei "s/#OF_CONF_DB_PORT#/$MYSQL_PORT/" /data/etc/openfire.xml && \
  sed -Ei "s/#OF_CONF_DB_USER_REPLACE#/$MYSQL_USER/" /data/etc/openfire.xml && \
  sed -Ei "s/#OF_CONF_DB_PASS_REPLACE#/$MYSQL_PASS/" /data/etc/openfire.xml && \
  sed -Ei "s/#OF_CONF_DB_NAME#/$MYSQL_DB/" /data/etc/openfire.xml
  
  cp -rf /data/etc/* /etc/openfire/
  rm -rf /data/etc
}

update_db(){
  echo "REPLACE INTO $MYSQL_DB.ofProperty(name, propValue) VALUES (\"plugin.userservice.enabled\", \"$USERSERVICE_ENABLE\");"
  $MYSQL_CONN -e "REPLACE INTO $MYSQL_DB.ofProperty(name, propValue) VALUES (\"plugin.userservice.enabled\", \"$USERSERVICE_ENABLE\");"
  echo "REPLACE INTO $MYSQL_DB.ofProperty(name, propValue) VALUES (\"plugin.userservice.secret\", \"$USER_SERVICE_SECRET\");"
  $MYSQL_CONN -e "REPLACE INTO $MYSQL_DB.ofProperty(name, propValue) VALUES (\"plugin.userservice.secret\", \"$USER_SERVICE_SECRET\");"
  echo "REPLACE INTO $MYSQL_DB.ofProperty(name, propValue) VALUES (\"xmpp.domain\", \"$XMPP_DOMAIN\");"
  $MYSQL_CONN -e "REPLACE INTO $MYSQL_DB.ofProperty(name, propValue) VALUES (\"xmpp.domain\", \"$XMPP_DOMAIN\");"
}

set_admin_passwd(){
  if [[ $ADMIN_PASSWD != "" ]]; then
    sed -Ei "s/'admin', 'admin', 'Administrator',/'admin', '$ADMIN_PASSWD', 'Administrator',/" /usr/share/openfire/resources/database/openfire_mysql.sql
  fi
}

create_log_dir
check_db
update_conf
set_admin_passwd

DAEMON_OPTS="-server \
    -DopenfireHome=/usr/share/openfire \
    -Dopenfire.lib.dir=/usr/share/openfire/lib \
    -classpath /usr/share/openfire/lib/startup.jar \
    -jar /usr/share/openfire/lib/startup.jar $*"
	
PIDFILE=/var/run/openfire.pid

echo "start openfire..."
start-stop-daemon -S --chuid $OPENFIRE_USER:$OPENFIRE_USER -b -m -p $PIDFILE --exec /usr/bin/java -- $DAEMON_OPTS
echo "sleep 30..."
sleep 30
echo "stop openfire..."	
start-stop-daemon -K -p $PIDFILE
echo "update_db...."
update_db
echo "restart openfire..."
exec start-stop-daemon -S --chuid $OPENFIRE_USER:$OPENFIRE_USER -m -p $PIDFILE --exec /usr/bin/java -- $DAEMON_OPTS


