#!/bin/bash
set -e

REDIS_USER=redis
REDIS_DATA_DIR=/var/lib/redis
REDIS_LOG_DIR=/var/log/redis
REDIS_SOCK_DIR=/run/redis
REDIS_CONF=/etc/redis/redis.conf

REDIS_PASSWORD=${REDIS_PASSWORD:-}
BIND_IP=${BIND_IP:-""}

create_socket_dir() {
  mkdir -p $REDIS_SOCK_DIR
  chmod -R 0755 $REDIS_SOCK_DIR
  chown -R $REDIS_USER:$REDIS_USER $REDIS_SOCK_DIR
}

create_data_dir() {
  mkdir -p $REDIS_DATA_DIR
  chmod -R 0755 $REDIS_DATA_DIR
  chown -R $REDIS_USER:$REDIS_USER $REDIS_DATA_DIR
}

create_log_dir() {
  mkdir -p $REDIS_LOG_DIR
  chmod -R 0755 $REDIS_LOG_DIR
  chown -R $REDIS_USER:$REDIS_USER $REDIS_LOG_DIR
}

update_conf() {
  if [[ $BIND_IP != "" ]]; then
	sed 's/^bind $BIND_IP/bind 0.0.0.0/' -i $REDIS_CONF
  fi
}

create_socket_dir
create_data_dir
create_socket_dir
update_conf

echo "Starting redis-server..."
exec start-stop-daemon --start --chuid $REDIS_USER:$REDIS_USER --exec $(which redis-server) -- $REDIS_CONF ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD} $*

