#!/bin/bash
set -e

REDIS_USER=redis
REDIS_DATA_DIR=/var/lib/redis
REDIS_LOG_DIR=/var/log/redis
REDIS_SERVER=/usr/local/bin/redis-server
REDIS_CONF=/usr/local/bin/redis.conf

REDIS_PASSWORD=${REDIS_PASSWORD:-}

create_user() {
  addgroup $REDIS_USER
  useradd  -p "S0dAmthh3vjPQ" -g $REDIS_USER  $REDIS_USER
}

create_data_dir() {
  mkdir -p $REDIS_DATA_DIR
  chmod -R 0755 $REDIS_DATA_DIR
  chown -R $REDIS_USER:$REDIS_USER $REDIS_DATA_DIR
}

create_log_dir() {
  mkdir -p $REDIS_LOG_DIR
  chmod -R 0755 $REDIS_LOG_DIR
  chown -R $REDIS_USER:$REDIS_USER $REDIS_LOG_DIR
}

update_conf() {
  # using '%' replace '/' to fix the expression error where REDIS_DATA_DIR has '/'
  sed -i "s%^dir ./%dir $REDIS_DATA_DIR%" $REDIS_CONF
  sed -i 's/^daemonize yes/daemonize no/'  $REDIS_CONF
  sed -i 's/^# unixsocket /unixsocket /' $REDIS_CONF
  sed -i 's/^# unixsocketperm 755/unixsocketperm 777/' $REDIS_CONF
}

create_user
create_data_dir
update_conf

echo "Starting redis-server..."
exec start-stop-daemon --start --chuid $REDIS_USER:$REDIS_USER --exec $REDIS_SERVER -- $REDIS_CONF ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD} $*

